/**:
  ros__parameters:
    map_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    use_odom_tf: true
    frequency: 10.0
    num_particles: 500
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_yaw_deg: 90.0
    motion_noise_xx: 0.1
    motion_noise_xy: 0.05
    motion_noise_yy: 0.1
    motion_noise_yaw_deg: 0.1
    normal_noise_position: 0.02
    normal_noise_orientation_deg: 2.0
    expansion_radius_position: 0.3
    expansion_radius_orientation_deg: 15.0
    laser_likelihood_max_dist: 0.3
    transform_tolerance: 0.5
    max_trajectory_length: 500
    reverse_y: false
    reverse_y_offset: 0.0
